/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    GenLabHeader: typeof import('./components/layouts/GenLabHeader.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconEpCopyDocument: typeof import('~icons/ep/copy-document')['default']
    IconEpDocument: typeof import('~icons/ep/document')['default']
    IconEpDocumentcopy: typeof import('~icons/ep/documentcopy')['default']
    IconEpDocumentCopy: typeof import('~icons/ep/document-copy')['default']
    IconEpEdit: typeof import('~icons/ep/edit')['default']
    IconFa6SolidHearPulse: typeof import('~icons/fa6-solid/hear-pulse')['default']
    IconFa6SolidHome: typeof import('~icons/fa6-solid/home')['default']
    JsonDocument: typeof import('./components/JsonDocument.vue')['default']
    LeftColumn: typeof import('./components/LeftColumn.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    MessageBoxDemo: typeof import('./components/MessageBoxDemo.vue')['default']
    RightColumn: typeof import('./components/RightColumn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    SideBarDrag: typeof import('./components/SideBarDrag.vue')['default']
    TestColumn: typeof import('./components/TestColumn.vue')['default']
    TitledDocument: typeof import('./components/TitledDocument.vue')['default']
  }
}
